# Generated by Django 4.1 on 2022-08-21 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_name', models.CharField(max_length=500, unique=True)),
                ('only_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Todo_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=500)),
                ('priority', models.CharField(choices=[('critical', 'critical'), ('high', 'high'), ('neutral', 'neutral'), ('low', 'low')], max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('assigned_to', models.CharField(max_length=500)),
                ('deadline', models.DateTimeField()),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.task_category')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todo')),
            ],
        ),
    ]
