# Generated by Django 4.1 on 2022-08-16 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=500)),
                ('only_admin', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backlog', models.BooleanField(default=0)),
                ('todo', models.BooleanField(default=0)),
                ('dev_started', models.BooleanField(default=0)),
                ('dev_completed', models.BooleanField(default=0)),
                ('review_started', models.BooleanField(default=0)),
                ('review_done', models.BooleanField(default=0)),
                ('closed', models.BooleanField(default=0)),
                ('remarks', models.BooleanField(default=0)),
                ('client_name', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(verbose_name='Date Created')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
