# Generated by Django 4.1 on 2022-08-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_only_admin_alter_projectdata_backlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
