# Generated by Django 4.1 on 2022-08-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_projectdata_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='only_admin',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='backlog',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='closed',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='dev_completed',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='dev_started',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='remarks',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='review_done',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='review_started',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='todo',
            field=models.BooleanField(default=0),
        ),
    ]
