# Generated by Django 4.1 on 2022-08-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_only_admin_alter_projectdata_backlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
