# Generated by Django 4.1 on 2022-08-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='backlog',
            field=models.BooleanField(default=True),
        ),
    ]
