# Generated by Django 4.1 on 2022-08-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_projectdata_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
