# Generated by Django 4.1 on 2022-08-25 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_projectdata_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=500)),
                ('client_address', models.CharField(max_length=500)),
                ('client_contact', models.CharField(max_length=500)),
                ('remarks', models.CharField(max_length=500)),
                ('year_of_work', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='client_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.client'),
        ),
    ]
