# Generated by Django 4.1 on 2022-08-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_client_alter_projectdata_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='remarks',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='client_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
