# Generated by Django 4.1 on 2022-08-25 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_client_remarks_alter_projectdata_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='client_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.client'),
        ),
    ]
